name: electro_app
description: "Electrical Device Monitoring App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.1
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.4.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/