// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGyJVoNZCso9ZxhdI0W_29i--B2alJnk',
    appId: '1:152632355525:web:141400ddd77c9507369eac',
    messagingSenderId: '152632355525',
    projectId: 'panel-monitor-691c6',
    authDomain: 'panel-monitor-691c6.firebaseapp.com',
    databaseURL: 'https://panel-monitor-691c6-default-rtdb.firebaseio.com',
    storageBucket: 'panel-monitor-691c6.firebasestorage.app',
    measurementId: 'G-6NWDDJFJPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYytQdzZcK-gMmM9nFFAu-B-UOI2M_ttQ',
    appId: '1:152632355525:android:c5e61fa4ad127cfd369eac',
    messagingSenderId: '152632355525',
    projectId: 'panel-monitor-691c6',
    databaseURL: 'https://panel-monitor-691c6-default-rtdb.firebaseio.com',
    storageBucket: 'panel-monitor-691c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoXlrNTU9Kq-0Pn4PwrOqSd8kKlWkaXM4',
    appId: '1:152632355525:ios:36c7ef2573f2ef63369eac',
    messagingSenderId: '152632355525',
    projectId: 'panel-monitor-691c6',
    databaseURL: 'https://panel-monitor-691c6-default-rtdb.firebaseio.com',
    storageBucket: 'panel-monitor-691c6.firebasestorage.app',
    androidClientId: '152632355525-ibj1kcqjr8v3ldhmqc2ntf28haqp9r90.apps.googleusercontent.com',
    iosClientId: '152632355525-rjs23v2o1sf80gjjvtbqd6433gkg91b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.electroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoXlrNTU9Kq-0Pn4PwrOqSd8kKlWkaXM4',
    appId: '1:152632355525:ios:36c7ef2573f2ef63369eac',
    messagingSenderId: '152632355525',
    projectId: 'panel-monitor-691c6',
    databaseURL: 'https://panel-monitor-691c6-default-rtdb.firebaseio.com',
    storageBucket: 'panel-monitor-691c6.firebasestorage.app',
    androidClientId: '152632355525-ibj1kcqjr8v3ldhmqc2ntf28haqp9r90.apps.googleusercontent.com',
    iosClientId: '152632355525-rjs23v2o1sf80gjjvtbqd6433gkg91b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.electroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdGyJVoNZCso9ZxhdI0W_29i--B2alJnk',
    appId: '1:152632355525:web:bc839252745ebc83369eac',
    messagingSenderId: '152632355525',
    projectId: 'panel-monitor-691c6',
    authDomain: 'panel-monitor-691c6.firebaseapp.com',
    databaseURL: 'https://panel-monitor-691c6-default-rtdb.firebaseio.com',
    storageBucket: 'panel-monitor-691c6.firebasestorage.app',
    measurementId: 'G-CRN45X891R',
  );
}
