name: Development Build

on:
  push:
    branches-ignore:
      - main
      - develop
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  quick_test:
    runs-on: ubuntu-latest
    name: Quick Tests & Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Check for TODO/FIXME comments
        run: |
          echo "Checking for TODO/FIXME comments..."
          if grep -r "TODO\|FIXME" lib/ --include="*.dart"; then
            echo "⚠️  Found TODO/FIXME comments in code"
            exit 0
          else
            echo "✅ No TODO/FIXME comments found"
          fi

  build_debug:
    runs-on: ubuntu-latest
    needs: quick_test
    name: Build Debug APK
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 3

  comment_pr:
    runs-on: ubuntu-latest
    needs: [quick_test, build_debug]
    name: Comment on PR
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 Debug build completed successfully! You can download the APK from the Actions artifacts.'
            })
