# Flutter Web Deploy to Firebase Hosting on merge - DISABLED
# Uncomment and configure FIREBASE_SERVICE_ACCOUNT_PANEL_MONITOR_691C6 secret to enable
name: Deploy Flutter Web to Firebase Hosting on merge (DISABLED)

on:
  # Disabled - uncomment when Firebase secret is configured
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Manual trigger only

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Flutter web
        run: flutter build web --release --web-renderer html

      # Disabled until Firebase service account is configured
      # - name: Deploy to Firebase Hosting
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: ${{ secrets.GITHUB_TOKEN }}
      #     firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PANEL_MONITOR_691C6 }}
      #     channelId: live
      #     projectId: panel-monitor-691c6

      - name: Firebase Deployment Disabled
        run: echo "Firebase deployment is disabled. Configure FIREBASE_SERVICE_ACCOUNT_PANEL_MONITOR_691C6 secret to enable."
